[package]
name = "rust"
version = "0.1.0"
edition = "2018"

# Optimize for size
# [profile.release]
# opt-level = "z"  # Optimize for size.
# lto = true
# codegen-units = 1
# panic = "abort"

[dependencies]
